#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : identify
Version  : 2.2.10
Release  : 2
URL      : https://files.pythonhosted.org/packages/15/9d/8cf65fd206ab42f80365057972cc412c97e2448180ce815b5baaac5a512a/identify-2.2.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/15/9d/8cf65fd206ab42f80365057972cc412c97e2448180ce815b5baaac5a512a/identify-2.2.10.tar.gz
Summary  : File identification library for Python
Group    : Development/Tools
License  : MIT
Requires: identify-bin = %{version}-%{release}
Requires: identify-python = %{version}-%{release}
Requires: identify-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
========

%package bin
Summary: bin components for the identify package.
Group: Binaries

%description bin
bin components for the identify package.


%package python
Summary: python components for the identify package.
Group: Default
Requires: identify-python3 = %{version}-%{release}

%description python
python components for the identify package.


%package python3
Summary: python3 components for the identify package.
Group: Default
Requires: python3-core
Provides: pypi(identify)

%description python3
python3 components for the identify package.


%prep
%setup -q -n identify-2.2.10
cd %{_builddir}/identify-2.2.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1623347720
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/identify-cli

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
